"""
Output Guardrail Engine for Pediatric Medical Assistant.
Provides verification and leak filtering before returning LLM responses to users.
"""

from dataclasses import dataclass, asdict
import logging
import re
from typing import Any, Dict, Optional

from .constants import (
    GuardrailViolationType,
    OUTPUT_LEAK_PATTERNS,
    OUTPUT_DANGEROUS_RECOMMENDATIONS,
    DATABASE_INJECTION_PATTERNS,
    PATH_TRAVERSAL_PATTERNS,
)

logger = logging.getLogger(__name__)

# Standard fallback when output is contaminated or leaks internal instructions
DEFAULT_OUTPUT_FALLBACK = (
    "I apologize, but I am unable to display the generated response as it did not meet our "
    "safety standards. Please rephrase your medical question or consult your healthcare provider directly."
)


@dataclass
class OutputGuardVerdict:
    """Standardized result returned by output validation checks."""
    safe: bool
    reason: str
    fallback_response: Optional[str] = None
    sanitized_output: Optional[str] = None
    details: Optional[Dict[str, Any]] = None

    @property
    def is_safe(self) -> bool:
        """Alias for compatibility with boolean naming conventions."""
        return self.safe

    def to_dict(self) -> Dict[str, Any]:
        """Serialize verdict to a standard dictionary."""
        return asdict(self)


class OutputGuard:
    """Production-grade validator for verifying LLM output safety and data loss prevention."""

    def __init__(self, fallback_message: str = DEFAULT_OUTPUT_FALLBACK):
        self.fallback_message = fallback_message

    def validate(self, model_response: Any) -> OutputGuardVerdict:
        """
        Validate model output against system leaks, raw SQL/NoSQL dumps, credentials, and medical boundary hazards.
        Guaranteed to fail-safe and return a structured verdict.
        """
        try:
            # 1. Type validation and text extraction
            response_text = model_response
            if isinstance(model_response, dict):
                response_text = model_response.get("content", "")
            elif hasattr(model_response, "content"):
                response_text = getattr(model_response, "content", "")

            if not isinstance(response_text, str):
                return OutputGuardVerdict(
                    safe=False,
                    reason=GuardrailViolationType.MALFORMED_INPUT.value,
                    fallback_response=self.fallback_message,
                    sanitized_output=None,
                    details={"error": "Model response must be a string or contain a content field."}
                )

            cleaned_output = response_text.strip()
            if not cleaned_output:
                return OutputGuardVerdict(
                    safe=False,
                    reason=GuardrailViolationType.MALFORMED_INPUT.value,
                    fallback_response=self.fallback_message,
                    sanitized_output="",
                    details={"error": "Model response is empty."}
                )

            # 2. System Prompt / Credential Leak Scanning
            for pattern in OUTPUT_LEAK_PATTERNS:
                match = pattern.search(cleaned_output)
                if match:
                    logger.critical(f"[Guardrails] System leak detected in model output: {match.group(0)}")
                    return OutputGuardVerdict(
                        safe=False,
                        reason=GuardrailViolationType.SYSTEM_PROMPT_LEAK_OUTPUT.value,
                        fallback_response=self.fallback_message,
                        sanitized_output=None,
                        details={"matched_token": match.group(0)}
                    )

            # 3. Infrastructure & Database Leak Scanning
            for pattern in DATABASE_INJECTION_PATTERNS:
                # Disallow raw SQL table structures/dumps accidentally generated by model
                match = pattern.search(cleaned_output)
                if match:
                    logger.warning(f"[Guardrails] Database artifact detected in model output: {match.group(0)}")
                    return OutputGuardVerdict(
                        safe=False,
                        reason=GuardrailViolationType.INFRASTRUCTURE_LEAK_OUTPUT.value,
                        fallback_response=self.fallback_message,
                        sanitized_output=None,
                        details={"matched_token": match.group(0)}
                    )

            for pattern in PATH_TRAVERSAL_PATTERNS:
                match = pattern.search(cleaned_output)
                if match:
                    logger.warning(f"[Guardrails] System path artifact detected in model output: {match.group(0)}")
                    return OutputGuardVerdict(
                        safe=False,
                        reason=GuardrailViolationType.INFRASTRUCTURE_LEAK_OUTPUT.value,
                        fallback_response=self.fallback_message,
                        sanitized_output=None,
                        details={"matched_token": match.group(0)}
                    )

            # 4. Dangerous Medical Recommendations Check
            for pattern in OUTPUT_DANGEROUS_RECOMMENDATIONS:
                match = pattern.search(cleaned_output)
                if match:
                    logger.critical(f"[Guardrails] Unsafe medical advice detected in model output: {match.group(0)}")
                    return OutputGuardVerdict(
                        safe=False,
                        reason=GuardrailViolationType.UNSAFE_MEDICAL_OUTPUT.value,
                        fallback_response=self.fallback_message,
                        sanitized_output=None,
                        details={"matched_token": match.group(0)}
                    )

            # Output is clean and safe to present
            return OutputGuardVerdict(
                safe=True,
                reason=GuardrailViolationType.NONE.value,
                fallback_response=None,
                sanitized_output=cleaned_output,
                details=None
            )

        except Exception as ex:
            logger.error(f"[Guardrails] Unexpected error during output validation: {str(ex)}", exc_info=True)
            return OutputGuardVerdict(
                safe=False,
                reason=GuardrailViolationType.INTERNAL_ERROR.value,
                fallback_response=self.fallback_message,
                sanitized_output=None,
                details={"exception": str(ex)}
            )


# Default singleton instance
_DEFAULT_OUTPUT_GUARD = OutputGuard()


def validateOutput(modelResponse: Any) -> OutputGuardVerdict:
    """
    Standard interface function to validate model response strings before returning to users.
    
    Args:
        modelResponse: The raw text string generated by the LLM.
        
    Returns:
        OutputGuardVerdict containing safety status, violation code, sanitized output, and fallback message.
    """
    return _DEFAULT_OUTPUT_GUARD.validate(modelResponse)


# Pythonic snake_case alias
validate_output = validateOutput
